[package]
name = "rust-demos"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.7", features = ["ws"] }
tokio = { version = "1", features = ["full"] }
tower = "0.4"
futures-util = "0.3"
uuid = { version = "1", features = ["v4"] }
chrono = "0.4"
